name: Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - tests/*
      - orc_api/*
      - pyproject.toml
  pull_request:
    branches: [ main ]
    paths:
      - tests/*
      - orc_api/*
      - pyproject.toml

jobs:
  Test-matrix:
    name: ${{ matrix.os }} - py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest" ] #, "macos-latest", "windows-latest"]
        python-version: ["3.9", "3.14"] # fix tests to oldest and newest supported versions

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        id: pysetup
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: pyproject.toml

      - name: Cache hit
        run: echo '${{ steps.pysetup.outputs.cache-hit }}'

      - name: OpenCV dependencies
        run: |
          sudo apt update
          sudo apt install libegl1 libopengl0 ffmpeg libjpeg-dev libfftw3-dev -y

      # build environment with pip
      - name: Install orc_api
        run: |
          pip install --upgrade pip
          pip install .[test,extra]

      # run all tests
      - name: Test
        run: python -m pytest --verbose --cov=orc_api --cov-report xml
      # upload test results to sonar cloud
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
